"""
Django settings for destiny_farm project.

Generated by 'django-admin startproject' using Django 5.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2@=-c@uvh@w(%epw=8%fl3*k!z&mppxqlra9l)#h@z!836quu4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    
    "destinyfarm4.com",
    "www.destinyfarm4.com",
    "3.6.87.103",
    
    "127.0.0.1",
    "https://36ad-103-5-135-107.ngrok-free.app",
]

# ALLOWED_HOSTS=["*"]
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'resort',
    'destiny_farm',
    
    'ckeditor',
    'ckeditor_uploader',
    "blog",

    'django.contrib.sites',
    'django.contrib.sitemaps',
    
    'rest_framework',
    'django_celery_beat',
    
    'corsheaders',
    
    # 'ratelimit',
]


SITE_ID = 2

SITE_URL = "https://destinyfarm4.com"

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'destiny_farm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'destiny_farm.wsgi.application'




# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'destiny_farmhouse',
        'USER': 'destiny_user',
        'PASSWORD': 'destiny@123',
        'HOST': '3.6.87.103',
        'PORT': '3306',
    }
}






# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = 'static/'

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# # Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Kolkata'

# ===============================
# CELERY BEAT SCHEDULE (AUTO SYNC ICAL)
# ===============================
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'sync-ical-every-10-minutes': {
        'task': 'resort.tasks.sync_all_calendars',
        'schedule': 600.0,  # every 10 minutes
    },
}


#razorpay 


RAZORPAY_KEY_ID = "rzp_live_SkSG1pAQO3WR4M"
RAZORPAY_KEY_SECRET = "6L813XIDAxv5vGFaq1H7iteG"
RAZORPAY_WEBHOOK_SECRET = "slkghlhsoSJKHUHHLHDLDLJDLJ@#@#32545hfdjjj//.,"


# rzp_live_SkSG1pAQO3WR4M

# 6L813XIDAxv5vGFaq1H7iteG

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'destanyfarm4@gmail.com'
EMAIL_HOST_PASSWORD = 'fndewughhucchaqz'
DEFAULT_FROM_EMAIL = 'destanyfarm4@gmail.com'
ADMIN_EMAIL = 'destanyfarm4@gmail.com' 

# FRONTEND_URL = 'http://127.0.0.1:9000'  

CC_EMAIL = [
    'anushamuraboina9@gmail.com',
    'laxminarayaninfotech1@gmail.com',
]
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_EMAIL_REQUIRED = True





RECAPTCHA_SITE_KEY = "6LeDIuEsAAAAAHjh2XlUAIPmoENdOKt6YT9VJ0Ta"
RECAPTCHA_SECRET_KEY = "6LeDIuEsAAAAAGZ_8-bRkbD4bQX4PlWyyJaXqFVQ"

# Django allauth (if you are using it)
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_EMAIL_REQUIRED = True


CKEDITOR_UPLOAD_PATH = "uploads/"
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:8000",
    "http://127.0.0.1:7000",
    "https://36ad-103-5-135-107.ngrok-free.app",
    
    "https://destinyfarm4.com",
    "https://www.destinyfarm4.com",

]



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = True


USE_X_FORWARDED_HOST = True


# BOOKING_RULES = {
#     "full": {
#         "check_in": "14:00",
#         "check_out": "11:00",
#         "next_day": True
#     },
#     "half": {
#         "check_in": "14:00",
#         "check_out": "23:00",
#         "next_day": False
#     }
# }