# Generated by Django 6.0.4 on 2026-04-30 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='slot',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
