# Generated by Django 6.0.4 on 2026-04-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0002_booking_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='slot',
            field=models.CharField(blank=True, choices=[('14:00-00:00', '02:00 PM – 12:00 AM'), ('01:00-10:00', '01:00 AM – 10:00 AM')], max_length=20, null=True),
        ),
    ]
