# Generated by Django 6.0.4 on 2026-04-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0003_alter_booking_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='villapricing',
            name='weekday_half_price',
            field=models.DecimalField(decimal_places=2, default=12000, max_digits=10),
        ),
        migrations.AddField(
            model_name='villapricing',
            name='weekend_half_price',
            field=models.DecimalField(decimal_places=2, default=15000, max_digits=10),
        ),
    ]
